---
title: "Foes Without Number"
output:
  md_document:
    variant: markdown_github
date: "2023-07-19"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(yaml)
```

## Table of template foes

```{r foesTbl, echo=FALSE}

foesTbl <- data.frame(hd = c(0:40)) %>% 
  mutate(effort = round(hd / 3),
         ac = round(9.6 + hd * (0.8 - (hd - 10) / 85), 0),
         att = round(hd * 0.6 + 2, 0),
         dc = att + 8,
         dmg = ceiling(pmax(2, (hd - 2) * 3 + 2.5)),
         skill5e = round(1.25 + hd / 4),
         skillWN = round(skill5e * 12 / 20),
         save = pmin(round(5.4 + hd / 3), 19)) %>%
  select(hd, effort, ac, save, dc, att, skill5e, skillWN, dmg)

knitr::kable(foesTbl, format = 'pipe')
```

## Foes ranks

```{r foesRank, echo=FALSE}

gauges <- data.frame(xp = c(0, 300, 900, 2700, 6500, 14000, 23000, 34000,
                              48000, 64000, 85000, 100000, 120000, 140000,
                              165000, 195000, 225000, 265000, 305000, 355000),
                       level = 1:20,
                       tier = c(rep(1, 4), rep(2, 6), rep(3, 6), rep(4, 4))) %>% 
  mutate(rank = as.integer(round((level - 1) / 3))) %>%
  filter(level %in% c(0:6 * 3 + 1)) %>%
  mutate(
    CRsolo = rank * 3 + tier + 1,
    CR1vs1 = round(CRsolo / 3 + (level - 8) * tier / 20, 1),
    CR2vs1 = round(CR1vs1 * 0.6 * 2, 1),
    CR4vs1 = round(CR1vs1 * 0.4 * 4, 1),
    CR1vs1m = round(CR1vs1 * 4),
    CR2vs1m = round(CR2vs1 * 4),
    CR4vs1m = round(CR4vs1 * 4),
    HDsolo = c(4, 13, 15, 18, 22, 25, 29),
    HD1vs1 = 4 * c(1, 4, 7, 9, 11, 13, 16),
    HD2vs1 = 4 * c(2, 5, 8, 10, 12, 15, 18),
    HD4vs1 = 4 * c(2, 5, 10, 12, 16, 18, 21),
    HDsoloT = (rank + 1) * 4,
    HD1vs1T = (rank * 10) + 5,
    HD2vs1T = (rank + 1) * 11 - 4,
    HD4vs1T = (rank + 1) * 13 - 4,
    hd_gauges = paste0('[', HDsoloT, ', ', HD1vs1T, ', ',
                       HD2vs1T, ', ', HD4vs1T, ']')) %>%
  select(level, tier, rank, hd_gauges)



rankTbl <- data.frame(rank = c(0:6)) %>% 
  mutate(hdGaugeSolo = (rank + 1) * 4 - 1,
         hdGaugeMob = hdGaugeSolo * 3 + 1,
         rankXP_partySession = 2000 * rank ^ 2) %>%
  left_join(gauges %>%
              select(rank, hd_gauges),
            by = 'rank')

knitr::kable(gauges, format = 'pipe')
```

