---
title: "efsa's fwn standards"
author: "efsa"
output:
  md_document:
    variant: markdown_github
date: "2023-08-28"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(googlesheets4)
library(dplyr)
library(tidyr)
library(ggplot2)
```

## Load and prepare data from Google Drive

```{r data}
fwnDB <- read_sheet('https://docs.google.com/spreadsheets/d/1xNTaAdvtE6mzDjzXhSQeA5TbIZo3pFzNen6mlMcThRA/edit#gid=1451095377')

fwnDB4plot <- fwnDB %>%
  select(hdc, hp, ac, dc, att, totdmg, Gm, Off, Def) %>%
  pivot_longer(cols = c('hp', 'ac', 'dc', 'att', 'totdmg', 'Off', 'Def'),
               names_to = 'variable',
               values_to = 'value')  

```

## Deffensive

Standard deffensive statistics:

```{r def1}

fwnDB4plot %>%
  filter(variable == 'hp') %>%
  ggplot(aes(x = hdc, y = value, colour = Gm)) +
  geom_jitter() +
  labs(y = 'hp')

fwnDB4plot %>%
  filter(variable == 'ac') %>%
  ggplot(aes(x = hdc, y = value, colour = Gm)) +
  geom_jitter() +
  labs(y = 'ac')

```

With expected deffensive rates:

```{r def2}

fwnDB4plot %>%
  filter(variable == 'Def') %>%
  ggplot(aes(x = hdc, y = value, colour = Gm)) +
  geom_jitter() +
  labs(y = 'Def')

```

## Offensive

Standard offensive statistics:

```{r off1}

fwnDB4plot %>%
  filter(variable == 'att') %>%
  ggplot(aes(x = hdc, y = value, colour = Gm)) +
  geom_jitter() +
  labs(y = 'att')

fwnDB4plot %>%
  filter(variable == 'totdmg') %>%
  ggplot(aes(x = hdc, y = value, colour = Gm)) +
  geom_jitter() +
  labs(y = 'totdmg')

```

With expected deffensive rates:

```{r off2}

fwnDB4plot %>%
  filter(variable == 'Off') %>%
  ggplot(aes(x = hdc, y = value, colour = Gm)) +
  geom_jitter() +
  labs(y = 'Off')

```